targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          - lib/**
      freezed:
        enabled: true
        generate_for:
          - lib/** 