name: gamification_wheel
# ========================================
# PROJECT DESCRIPTION
# ========================================
description: A fully customizable gamification wheel Flutter widget with Clean Architecture and BLoC pattern. Perfect for games, decision-making, and interactive applications.
version: 0.1.4
homepage: https://github.com/Tahaylmz/gamification-wheel
repository: https://github.com/Tahaylmz/gamification-wheel
issue_tracker: https://github.com/Tahaylmz/gamification-wheel/issues
documentation: https://github.com/Tahaylmz/gamification-wheel#readme

# ========================================
# ENVIRONMENT AND SDK VERSION
# ========================================
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

# ========================================
# MAIN DEPENDENCIES
# ========================================
dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # =====================
  # UI & Animation Packages
  # =====================
  flutter_spinkit: ^5.2.1   # Loading animations
  vector_math: ^2.1.4        # Vector math operations

  # =====================
  # State Management & BLoC
  # =====================
  flutter_bloc: ^9.1.1      # BLoC state management
  bloc: ^9.0.0              # BLoC core
  equatable: ^2.0.7         # State comparison

  # =====================
  # Dependency Injection
  # =====================
  get_it: ^8.0.3            # Service locator

  # =====================
  # Utility & Functional
  # =====================
  dartz: ^0.10.1            # Functional programming utils

# ========================================
# DEVELOPER DEPENDENCIES
# ========================================
dev_dependencies:
  # Lint and Test
  flutter_lints: ^3.0.2     # Code quality and linter
  flutter_test:
    sdk: flutter            # Flutter test framework

# ========================================
# FLUTTER SPECIFIC SETTINGS
# ========================================
flutter:
  uses-material-design: true
  
  # =====================
  # ASSETS
  # =====================
  assets:
    - assets/gifs/
  
  # =====================
  # FONTS
  # =====================